/*global systemDictionary:true */
'use strict';

systemDictionary = {
    'dspamp adapter settings':        {
        'en':    'Adapter settings for dspamp',
        'de':    'Adaptereinstellungen für dspamp',
        'ru':    'Настройки адаптера для dspamp',
        'pt':    'Configurações do adaptador para dspamp',
        'nl':    'Adapterinstellingen voor dspamp',
        'fr':    'Paramètres d\'adaptateur pour dspamp',
        'it':    'Impostazioni dell\'adattatore per dspamp',
        'es':    'Ajustes del adaptador para dspamp',
        'pl':    'Ustawienia adaptera dla dspamp',
        'zh-cn': 'dspamp的适配器设置'
    },
    'option1':                        {
        'en':    'option1',
        'de':    'Option 1',
        'ru':    'Опция 1',
        'pt':    'Opção 1',
        'nl':    'Optie 1',
        'fr':    'Option 1',
        'it':    'opzione 1',
        'es':    'Opción 1',
        'pl':    'opcja 1',
        'zh-cn': '选项1'
    },
    'option2':                        {
        'en':    'option2',
        'de':    'Option 2',
        'ru':    'option2',
        'pt':    'opção 2',
        'nl':    'Optie 2',
        'fr':    'Option 2',
        'it':    'opzione 2',
        'es':    'opcion 2',
        'pl':    'Opcja 2',
        'zh-cn': '选项2'
    },
    'myColor':                        {
        'en':    'myColor',
        'de':    'meineColor',
        'ru':    'Мой цвет',
        'pt':    'minhaCor',
        'nl':    'mijnKleur',
        'fr':    'maCouleur',
        'it':    'mioColore',
        'es':    'miColor',
        'pl':    'mójKolor',
        'zh-cn': '我的颜色'
    },
    'myColor_tooltip':                {
        'en':    'Description of\nmyColor',
        'de':    'Beschreibung von\nmyColor',
        'ru':    'Описание\nmyColor',
        'pt':    'Descrição de\nmyColor',
        'nl':    'Beschrijving van\nmyColor',
        'fr':    'Description de\nmyColor',
        'it':    'Descrizione di\nmyColor',
        'es':    'Descripción de\nmyColor',
        'pl':    'Opis\nmyColor',
        'zh-cn': '\nmyColor的描述'
    },
    'htmlText':                       {
        'en':    'htmlText',
        'de':    'htmlText',
        'ru':    'htmlText',
        'pt':    'htmlText',
        'nl':    'htmlText',
        'fr':    'htmlText',
        'it':    'htmlText',
        'es':    'htmlText',
        'pl':    'htmlText',
        'zh-cn': 'htmlText'
    },
    'group_extraMyset':               {
        'en':    'extraMyset',
        'de':    'extraMyset',
        'ru':    'extraMyset',
        'pt':    'extraMyset',
        'nl':    'extraMyset',
        'fr':    'extraMyset',
        'it':    'extraMyset',
        'es':    'extraMyset',
        'pl':    'extraMyset',
        'zh-cn': 'extraMyset'
    },
    'extraAttr':                      {
        'en':    'extraAttr',
        'de':    'extraAttr',
        'ru':    'extraAttr',
        'pt':    'extraAttr',
        'nl':    'extraAttr',
        'fr':    'extraAttr',
        'it':    'extraAttr',
        'es':    'extraAttr',
        'pl':    'extraAttr',
        'zh-cn': 'extraAttr'
    },
    'Instance':                       {
        'en':    'Instance',
        'de':    'Instanz',
        'ru':    'Инстанция',
        'pt':    'Instância',
        'nl':    'Instantie',
        'fr':    'Instance',
        'it':    'Esempio',
        'es':    'Instancia',
        'pl':    'Instancja',
        'zh-cn': '例'
    },
    'main settings':                  {
        'en':    'main settings',
        'de':    'Haupteinstellungen',
        'ru':    'Основные настройки',
        'pt':    'configurações principais',
        'nl':    'belangrijkste instellingen',
        'fr':    'Réglages principaux',
        'it':    'impostazioni principali',
        'es':    'ajustes principales',
        'pl':    'Ustawienia główne',
        'zh-cn': '主要设置'
    },
    'settings zone':                  {
        'en':    'zones settings',
        'de':    'Zoneneinstellungen',
        'ru':    'Настройка зон',
        'pt':    'configurações de zonas',
        'nl':    'zones instellingen',
        'fr':    'paramètres des zones',
        'it':    'impostazioni delle zone',
        'es':    'ajustes de zonas',
        'pl':    'ustawienia stref',
        'zh-cn': '区域设置'
    },
    'settings input':                 {
        'en':    'Inputs settings',
        'de':    'Eingabeeinstellungen',
        'ru':    'Настройки входов',
        'pt':    'Configurações de entradas',
        'nl':    'Ingangen instellingen',
        'fr':    'Paramètres des entrées',
        'it':    'Impostazioni degli ingressi',
        'es':    'Configuración de entradas',
        'pl':    'Ustawienia wejść',
        'zh-cn': '输入设置'
    },
    'settings device':                {
        'en':    'settings device',
        'de':    'Einstellungen Gerät',
        'ru':    'Настройки устройства',
        'pt':    'dispositivo de configurações',
        'nl':    'instellingen apparaat',
        'fr':    'paramètres appareil',
        'it':    'impostazioni dispositivo',
        'es':    'dispositivo de configuración',
        'pl':    'urządzenie ustawień',
        'zh-cn': '设置设备'
    },
    'host':                           {
        'en':    'Host IP ',
        'de':    'Host-IP',
        'ru':    'IP-адрес хоста',
        'pt':    'IP do host',
        'nl':    'Host-IP',
        'fr':    'IP hôte',
        'it':    'IP host',
        'es':    'IP de host',
        'pl':    'Adres IP hosta',
        'zh-cn': '主机IP'
    },
    'port':                           {
        'en':    'Port',
        'de':    'Hafen',
        'ru':    'Порт',
        'pt':    'Porta',
        'nl':    'Haven',
        'fr':    'Port',
        'it':    'Porta',
        'es':    'Puerto',
        'pl':    'Port',
        'zh-cn': '港口'
    },
    'def':                            {
        'en':    'Default 81',
        'de':    'Standard 81',
        'ru':    'По умолчанию 81',
        'pt':    'Padrão 81',
        'nl':    'Standaard 81',
        'fr':    'Par défaut 81',
        'it':    '81 . predefinito',
        'es':    'Por defecto 81',
        'pl':    'Domyślnie 81',
        'zh-cn': '默认 81'
    },
    'DSP Amplifier configuration':    {
        'en':    'DSP Amplifier configuration',
        'de':    'DSP-Verstärkerkonfiguration',
        'ru':    'Конфигурация усилителя DSP',
        'pt':    'Configuração do amplificador DSP',
        'nl':    'DSP-versterkerconfiguratie',
        'fr':    'Configuration de l\'amplificateur DSP',
        'it':    'Configurazione dell\'amplificatore DSP',
        'es':    'Configuración del amplificador DSP',
        'pl':    'Konfiguracja wzmacniacza DSP',
        'zh-cn': 'DSP 放大器配置'
    },
    'host_name':                      {
        'en':    'Host name',
        'de':    'Hostname',
        'ru':    'Имя хоста',
        'pt':    'Nome de anfitrião',
        'nl':    'Hostnaam',
        'fr':    'Nom d\'hôte',
        'it':    'Nome host',
        'es':    'Nombre de host',
        'pl':    'Nazwa hosta',
        'zh-cn': '主机名'
    },
    'use_mqtt':                       {
        'en':    'Using mqtt',
        'de':    'mqtt . verwenden',
        'ru':    'Использовать MQTT',
        'pt':    'Usando mqtt',
        'nl':    'mqtt . gebruiken',
        'fr':    'Utilisation de mqtt',
        'it':    'Usando mqtt',
        'es':    'Usando mqtt',
        'pl':    'Korzystanie z mqtt',
        'zh-cn': '使用 mqtt'
    },
    'Add input device':               {
        "en": "Add audio input device",
        "de": "Audioeingabegerät hinzufügen",
        "ru": "Добавить устройство ввода звука",
        "pt": "Adicionar dispositivo de entrada de áudio",
        "nl": "Audio-invoerapparaat toevoegen",
        "fr": "Ajouter un périphérique d'entrée audio",
        "it": "Aggiungi dispositivo di ingresso audio",
        "es": "Agregar dispositivo de entrada de audio",
        "pl": "Dodaj urządzenie wejściowe audio",
        "zh-cn": "添加音频输入设备"
    },
    'name input':                     {
        "en": "Input name",
        "de": "Name eingeben",
        "ru": "Имя входа",
        "pt": "Nome de entrada",
        "nl": "Invoernaam",
        "fr": "Nom d'entrée",
        "it": "Inserisci il nome",
        "es": "Nombre de entrada",
        "pl": "Wpisz nazwę",
        "zh-cn": "输入名称"
    },
    'MQTT configuration':             {
        'en':    'MQTT configuration',
        'de':    'MQTT-Konfiguration',
        'ru':    'Конфигурация MQTT',
        'pt':    'Configuração MQTT',
        'nl':    'MQTT-configuratie',
        'fr':    'Configuration MQTT',
        'it':    'Configurazione MQTT',
        'es':    'Configuración MQTT',
        'pl':    'Konfiguracja MQTT',
        'zh-cn': 'MQTT 配置'
    },
    'mqtt_server':                    {
        'en':    'MQTT server',
        'de':    'MQTT-Server',
        'ru':    'MQTT сервер',
        'pt':    'Servidor MQTT',
        'nl':    'MQTT-server',
        'fr':    'serveur MQTT',
        'it':    'Server MQTT',
        'es':    'Servidor MQTT',
        'pl':    'Serwer MQTT',
        'zh-cn': 'MQTT 服务器'
    },
    'mqtt_port':                      {
        'en':    'MQTT port',
        'de':    'MQTT-Port',
        'ru':    'MQTT порт',
        'pt':    'Porta MQTT',
        'nl':    'MQTT-poort',
        'fr':    'Port MQTT',
        'it':    'Porta MQTT',
        'es':    'Puerto MQTT',
        'pl':    'Port MQTT',
        'zh-cn': 'MQTT 端口'
    },
    'desc mqtt_port':                 {
        'en':    'Default 1883',
        'de':    'Standard 1883',
        'ru':    'По умолчанию 1883',
        'pt':    'Padrão 1883',
        'nl':    'Standaard 1883',
        'fr':    'Par défaut 1883',
        'it':    'Predefinito 1883',
        'es':    'Por defecto 1883',
        'pl':    'Domyślnie 1883',
        'zh-cn': '默认 1883'
    },
    'retain flag':                    {
        'en':    'Отправлять \'Retain\' flag',
        'de':    'тправлять \'Beibehalten\'-Flag',
        'ru':    'Отправлять флаг \'Retain\'',
        'pt':    'Отправлять \'Retain\' flag',
        'nl':    'авлять \'Behoud\' vlag',
        'fr':    'тправлять Drapeau \'Conserver\'',
        'it':    'тправлять Bandiera \'Conserva\'',
        'es':    'Отправлять la bandera \'Retener\'',
        'pl':    'Отправлять „Zatrzymaj” flagę',
        'zh-cn': 'Отправлять \'保留\'标志'
    },
    'set_topic':                      {
        'en':    'Using topics \'SET\'',
        'de':    'Verwenden von Themen \'SET\'',
        'ru':    'Использовать топики \'SET\'',
        'pt':    'Usando tópicos \'SET\'',
        'nl':    'Onderwerpen \'SET\' gebruiken',
        'fr':    'Utilisation des sujets \'SET\'',
        'it':    'Utilizzo di argomenti \'SET\'',
        'es':    'Uso de temas \'SET\'',
        'pl':    'Korzystanie z tematów „SET”',
        'zh-cn': '使用主题“SET”'
    },
    'mqtt_user':                      {
        'en':    'MQTT user',
        'de':    'MQTT-Benutzer',
        'ru':    'Пользователь MQTT',
        'pt':    'Usuário MQTT',
        'nl':    'MQTT-gebruiker',
        'fr':    'Utilisateur MQTT',
        'it':    'Utente MQTT',
        'es':    'Usuario de MQTT',
        'pl':    'Użytkownik MQTT',
        'zh-cn': 'MQTT用户'
    },
    'mqtt_pass':                      {
        'en':    'MQTT password',
        'de':    'MQTT-Passwort',
        'ru':    'Пароль MQTT',
        'pt':    'Senha MQTT',
        'nl':    'MQTT-wachtwoord',
        'fr':    'Mot de passe MQTT',
        'it':    'Password MQTT',
        'es':    'Contraseña MQTT',
        'pl':    'Hasło MQTT',
        'zh-cn': 'MQTT 密码'
    },
    'mqtt_client_id':                 {
        'en':    'MQTT client id',
        'de':    'MQTT-Client-ID',
        'ru':    'Идентификатор клиента MQTT',
        'pt':    'ID do cliente MQTT',
        'nl':    'MQTT-client-ID',
        'fr':    'ID client MQTT',
        'it':    'ID client MQTT',
        'es':    'ID de cliente MQTT',
        'pl':    'Identyfikator klienta MQTT',
        'zh-cn': 'MQTT 客户端 ID'
    },
    'mqtt_topic':                     {
        'en':    'Main MQTT topic',
        'de':    'Hauptthema MQTT',
        'ru':    'Основной MQTT топик',
        'pt':    'Tópico MQTT principal',
        'nl':    'Belangrijkste MQTT-onderwerp',
        'fr':    'Sujet principal MQTT',
        'it':    'Argomento principale MQTT',
        'es':    'Tema principal de MQTT',
        'pl':    'Główny temat MQTT',
        'zh-cn': '主要 MQTT 主题'
    },
    'upload config file':             {
        'en':    'Upload config file',
        'de':    'Konfigurationsdatei hochladen',
        'ru':    'Загрузить файл конфигурации',
        'pt':    'Carregar arquivo de configuração',
        'nl':    'Configuratiebestand uploaden',
        'fr':    'Télécharger le fichier de configuration',
        'it':    'Carica file di configurazione',
        'es':    'Subir archivo de configuración',
        'pl':    'Prześlij plik konfiguracyjny',
        'zh-cn': '上传配置文件'
    },
    'choose file':                    {
        'en':    'Choose file',
        'de':    'Datei wählen',
        'ru':    'Выберите файл',
        'pt':    'Escolher arquivo',
        'nl':    'Kies bestand',
        'fr':    'Choisir le fichier',
        'it':    'Scegli il file',
        'es':    'Elija el archivo',
        'pl':    'Wybierz plik',
        'zh-cn': '选择文件'
    },
    'Accepted File Types : .h, .xml': {
        'en':    'Accepted File Types : *.h, *.xml',
        'de':    'Akzeptierte Dateitypen: *.h, *.xml',
        'ru':    'Допустимые типы файлов: *.h, *.xml',
        'pt':    'Tipos de arquivo aceitos: *.h, *.xml',
        'nl':    'Geaccepteerde bestandstypen: *.h, *.xml',
        'fr':    'Types de fichiers acceptés : *.h, *.xml',
        'it':    'Tipi di file accettati: *.h, *.xml',
        'es':    'Tipos de archivos aceptados: *.h, *.xml',
        'pl':    'Akceptowane typy plików: *.h, *.xml',
        'zh-cn': '接受的文件类型： *.h, *.xml'
    },
    'Add zone':                       {
        'en':    'Add zone',
        'de':    'Zone hinzufügen',
        'ru':    'Добавить зону',
        'pt':    'Adicionar zona',
        'nl':    'Zone toevoegen',
        'fr':    'Ajouter une zone',
        'it':    'Aggiungi zona',
        'es':    'Agregar zona',
        'pl':    'Dodaj strefę',
        'zh-cn': '添加区域'
    },
    'name zone':                      {
        'en':    'Name zone',
        'de':    'Namenszone',
        'ru':    'Имя зоны',
        'pt':    'Zona de nome',
        'nl':    'Naam zone',
        'fr':    'Zone de nom',
        'it':    'Nome zona',
        'es':    'Zona de nombre',
        'pl':    'Nazwij strefę',
        'zh-cn': '名称区'
    },
    'Save to device':                 {
        'en':    'Save to device',
        'de':    'Auf Gerät speichern',
        'ru':    'Сохранить на устройство',
        'pt':    'Salvar no dispositivo',
        'nl':    'Opslaan op apparaat',
        'fr':    'Enregistrer sur l\'appareil',
        'it':    'Salva sul dispositivo',
        'es':    'Guardar en el dispositivo',
        'pl':    'Zapisz na urządzeniu',
        'zh-cn': '保存到设备'
    },
    'Сheck':                          {
        'en':    'Сheck',
        'de':    'verdammt',
        'ru':    'Проверить',
        'pt':    'Сheck',
        'nl':    'heck',
        'fr':    'bon sang',
        'it':    'diamine',
        'es':    'Verificar',
        'pl':    'Sprawdź',
        'zh-cn': '检查'
    },
    'Upload config files':            {
        'en':    'Upload config files',
        'de':    'Konfigurationsdateien hochladen',
        'ru':    'Загрузите файлы конфигурации',
        'pt':    'Carregar arquivos de configuração',
        'nl':    'Configuratiebestanden uploaden',
        'fr':    'Télécharger des fichiers de configuration',
        'it':    'Carica file di configurazione',
        'es':    'Subir archivos de configuración',
        'pl':    'Prześlij pliki konfiguracyjne',
        'zh-cn': '上传配置文件'
    },
    'Files':                          {
        'en':    'Files',
        'de':    'Dateien',
        'ru':    'Файлы',
        'pt':    'arquivos',
        'nl':    'Bestanden',
        'fr':    'Des dossiers',
        'it':    'File',
        'es':    'Archivos',
        'pl':    'Pliki',
        'zh-cn': '文件'
    }
};